<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_uname</name>
   <tag></tag>
   <elementGuidId>e2183e26-67a5-4fc5-a04c-c875aa54a43c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>386d876c-0fca-4eff-a30c-ea48adc2733e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e9b5b461-072b-45f6-b848-f40811134942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uname</value>
      <webElementGuid>cb6d5e8d-afa4-46f7-b92c-d6bb1d05cd43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>test</value>
      <webElementGuid>e1ec16d8-022d-4125-9ce2-c99e9da8b7f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>uname</value>
      <webElementGuid>869ce78a-4466-4d30-86da-e65d05a3230e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uname&quot;)</value>
      <webElementGuid>5412ba16-3df8-4b74-a671-a89af3bccc69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uname']</value>
      <webElementGuid>c9060e26-1c9a-46d4-9fae-2836915ab10a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f709afee-1339-45c1-ac8a-0b1420aac4f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'uname' and @placeholder = 'test' and @name = 'uname']</value>
      <webElementGuid>ab7bdf38-d444-4b07-a6af-cbea6511c7e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
